language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"

notifications:
    email: false

sudo: false

before_script:
  - git clone https://github.com/bookbrainz/bookbrainz-sql.git
  - cp ./test/bookshelf.js.example ./test/bookshelf.js
  - psql -c 'CREATE DATABASE bookbrainz_test;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp"; CREATE SCHEMA musicbrainz; CREATE SCHEMA bookbrainz;' -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/schemas/musicbrainz.sql -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/schemas/bookbrainz.sql -d bookbrainz_test -U postgres

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: 97a40fc81268050098a14f76f2befa7b19d548a073b63d852fd89b9cf524afc2
